apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress-1
  annotations:
    nginx.ingress.kubernetes.io/custom-headers: {{ .Release.Namespace }}/custom-security-headers
    checksum/config: {{ include (print $.Template.BasePath "/custom-security-headers-configmap.yaml") . | sha256sum }}
spec:
  rules:
  - host: podinfo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port:
              number: 9898